vim.api.nvim_set_keymap("n", "<leader>ff", ":Telescope find_files<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<leader>fg", ":Telescope live_grep<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<leader>fb", ":Telescope buffers<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<leader>fh", ":Telescope help_tags<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<leader>e", ":Telescope file_browser<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<leader>mm", ":%s/\\r//<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<leader>t", ":tabnew<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<leader>cf", ":e %:h/", { noremap = true, silent = true })
vim.api.nvim_set_keymap("i", "(", "()<Left>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("i", "[", "[]<left>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("i", "{", "{}<Left>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<left>", "<cmd>echo 'use h instead!'<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<right>", "<cmd>echo 'use l instead!'<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<down>", "<cmd>echo 'use j instead!'<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<up>", "<cmd>echo 'use k instead!'<CR>", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-d>", "<C-d>zz", { noremap = true, silent = true })
vim.api.nvim_set_keymap("n", "<C-u>", "<C-u>zz", { noremap = true, silent = true })
vim.keymap.set("i", "<Esc>", "<C-c>", { noremap = true, silent = true })

vim.keymap.set("n", "<leader>se", function()
  vim.diagnostic.open_float(nil, { focus = false, border = "rounded" })
end, { desc = "Show diagnostic error message" })
